package org.example.lab1.mybatis.model;

public class Campaign {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAMPAIGN.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAMPAIGN.LENGTH
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAMPAIGN.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAMPAIGN.DUNGEON_MASTER_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer dungeonMasterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAMPAIGN.ID
     *
     * @return the value of PUBLIC.CAMPAIGN.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAMPAIGN.ID
     *
     * @param id the value for PUBLIC.CAMPAIGN.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAMPAIGN.LENGTH
     *
     * @return the value of PUBLIC.CAMPAIGN.LENGTH
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAMPAIGN.LENGTH
     *
     * @param length the value for PUBLIC.CAMPAIGN.LENGTH
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAMPAIGN.NAME
     *
     * @return the value of PUBLIC.CAMPAIGN.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAMPAIGN.NAME
     *
     * @param name the value for PUBLIC.CAMPAIGN.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAMPAIGN.DUNGEON_MASTER_ID
     *
     * @return the value of PUBLIC.CAMPAIGN.DUNGEON_MASTER_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getDungeonMasterId() {
        return dungeonMasterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAMPAIGN.DUNGEON_MASTER_ID
     *
     * @param dungeonMasterId the value for PUBLIC.CAMPAIGN.DUNGEON_MASTER_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setDungeonMasterId(Integer dungeonMasterId) {
        this.dungeonMasterId = dungeonMasterId;
    }
}