package org.example.lab1.mybatis.model;

public class Classes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CLASSES.TITLE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLASSES.ID
     *
     * @return the value of PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLASSES.ID
     *
     * @param id the value for PUBLIC.CLASSES.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CLASSES.TITLE
     *
     * @return the value of PUBLIC.CLASSES.TITLE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CLASSES.TITLE
     *
     * @param title the value for PUBLIC.CLASSES.TITLE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setTitle(String title) {
        this.title = title;
    }
}