package org.example.lab1.mybatis.model;

public class Person {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.ID
     *
     * @return the value of PUBLIC.PERSON.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.ID
     *
     * @param id the value for PUBLIC.PERSON.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.NAME
     *
     * @return the value of PUBLIC.PERSON.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.NAME
     *
     * @param name the value for PUBLIC.PERSON.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PERSON.SURNAME
     *
     * @return the value of PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PERSON.SURNAME
     *
     * @param surname the value for PUBLIC.PERSON.SURNAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }
}