package org.example.lab1.mybatis.model;

public class Playercharacter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERCHARACTER.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERCHARACTER.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERCHARACTER.RACE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private String race;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PLAYERCHARACTER.PERSON_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    private Integer personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERCHARACTER.ID
     *
     * @return the value of PUBLIC.PLAYERCHARACTER.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERCHARACTER.ID
     *
     * @param id the value for PUBLIC.PLAYERCHARACTER.ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERCHARACTER.NAME
     *
     * @return the value of PUBLIC.PLAYERCHARACTER.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERCHARACTER.NAME
     *
     * @param name the value for PUBLIC.PLAYERCHARACTER.NAME
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERCHARACTER.RACE
     *
     * @return the value of PUBLIC.PLAYERCHARACTER.RACE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public String getRace() {
        return race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERCHARACTER.RACE
     *
     * @param race the value for PUBLIC.PLAYERCHARACTER.RACE
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setRace(String race) {
        this.race = race;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PLAYERCHARACTER.PERSON_ID
     *
     * @return the value of PUBLIC.PLAYERCHARACTER.PERSON_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public Integer getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PLAYERCHARACTER.PERSON_ID
     *
     * @param personId the value for PUBLIC.PLAYERCHARACTER.PERSON_ID
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    public void setPersonId(Integer personId) {
        this.personId = personId;
    }
}