package org.example.lab1.mybatis.dao;

import java.util.List;
import org.example.lab1.mybatis.model.Campaign;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CampaignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAMPAIGN
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAMPAIGN
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int insert(Campaign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAMPAIGN
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    Campaign selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAMPAIGN
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    List<Campaign> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAMPAIGN
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int updateByPrimaryKey(Campaign record);
}