package org.example.lab1.mybatis.dao;

import java.util.List;
import org.example.lab1.mybatis.model.Person;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    List<Person> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PERSON
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int updateByPrimaryKey(Person record);
}