package org.example.lab1.mybatis.dao;

import java.util.List;
import org.example.lab1.mybatis.model.Playercharacter;
import org.mybatis.cdi.Mapper;

@Mapper
public interface PlayercharacterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERCHARACTER
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERCHARACTER
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int insert(Playercharacter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERCHARACTER
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    Playercharacter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERCHARACTER
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    List<Playercharacter> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PLAYERCHARACTER
     *
     * @mbg.generated Mon Apr 29 00:19:48 EEST 2024
     */
    int updateByPrimaryKey(Playercharacter record);
}